#
//  ios.yml
//  CrimeNearMe
//
//  Created by Mylo on 31/08/2025.
//

name: iOS Build

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.4'   # or whatever version you use locally

      - name: Build
        run: |
          xcodebuild -scheme CrimeNearMe \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            build | xcpretty
